apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-core
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-events-core
  namespace: argo-events
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - pods
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-core
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-core
subjects:
  - kind: ServiceAccount
    name: argo-events-core
    namespace: argo-events