apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /git/argoproj
          name: argoproj1
    volumes:
      - name: argoproj1
        emptyDir: {}
#    serviceAccountName: operate-workflow-sa
    serviceAccountName: argo-events-core
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            git:
              url: "https://github.com/chandrakumarbhanu/go-api.git"
              cloneDirectory: "/git/argoproj"
              creds:
                username:
                  name: "github-secret"
                  key: username
                password:
                  name: "github-secret"
                  key: password
              filePath: "r2c-ci.yaml"
              branch: main        